#!/bin/bash
# DiscordTexttoSpeech
# Author: kickash32
# Version: 1.0 1st Release on 6 Oct 2017

file=$1
fileout=$2

declare -A name2voice
declare -a voices

tmpAIFF="tmp.aiff"
tmpMP3="tmp.mp3"
log="dt2p.log"
out="out.mp3"

language="en_"
i=0

function help {
echo ""
echo "Usage: dts inputfile outputfile [language_]"
echo "Example: dts discordArchive.txt wednesday.mp3"
echo "Example: dts TTS.txt voices.mp3 en_"
echo "Utilizes 'say' and 'lame' to stitch together an mp3 file with different voices for each person from a discord channel archive"
echo "Requires BASH 4.0+ and LAME installed, recommended to have sufficient say voices installed"
}

tmp="$(echo `say -v ? | grep -E ".{0,32}en_" -o`)"
for word in $tmp
do
	if test $word != $language
	then
		echo "Detected installed $language voice: $word"
    	voices["$i"]="$word"
    	i="$(($i+1))"
    fi
done

i=0

if test "$file" != "" && test -e $file && test -r $file
then
	#touch "$log"
	echo "" > "$out"
	while read line
	do
		convoDate="$(echo "$line"|grep -E " - (?:Last (?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|Yesterday|Today|[0-9]{2}/[0-9]{2}/[0-9]{4})" -o)"
		if test "$convoDate" != ""
		then
			tmp="$(echo "$line"|grep -E ".{0,32}$convoDate" -o)"
			#echo "tmp is $tmp"
			name="${tmp:0:${#tmp}-${#convoDate}}"
			currentv="${name2voice[$name]}"
			
			if test "$currentv" == ""
			then
				name2voice["$name"]="${voices[$i]}"
				i="$(($i+1))"
			fi
			currentv="${name2voice[$name]}"
			
			echo "Detected user change to $name, using voice $currentv"
			
			say -v "$currentv" "$name says" -o "$tmpAIFF"
			lame "$tmpAIFF" --quiet
			cat "$tmpMP3" >> "$out"
		else
			if test "$currentv" == ""
			then
				say "$line" -o "$tmpAIFF"
			else
				say -v "$currentv" "$line" -o "$tmpAIFF"
			fi
			
			lame "$tmpAIFF" --quiet
			cat "$tmpMP3" >> "$out"
		fi
	done < $file
	cp "$out" "$fileout"
	rm "$tmpAIFF"
	rm "$tmpMP3"
	rm "$out"
	#rm "$log"
elif test ! -e $file || test "$file" == ""
then
	echo "File '$file' does not exist."
	help
else
	echo "File '$file' is not readable."
fi
